---
title: "Links"
---

Always growing list of cool, free learning/fun/useful resources out there that will make you love the internet.

## Tutorials
  - [calmcode](http://calmcode.io): A goldmine – learn calmly bit by bit with hands-on tutorials.
  - [Real Python](https://realpython.com/): Awesome in depth tutorials about all sorts of aspects of the language.
  - [Scipy Lectures](http://scipy-lectures.org): Learn numerics, scientific and data oriented Python.
  - [Numba - Tell Those C++ Bullies to Get Lost - Forsyth & Barba - SciPy 2017](https://www.youtube.com/watch?v=SzBi3xdEF2Y&list=PLYx7XA2nY5Gf37zYZMw6OqGFRPjB1jCy6&index=7)
  - [Reproducible workflow in Jupyter - Jake van der Plas](https://www.youtube.com/playlist?list=PLYCpMb24GpOC704uO9svUrihl-HY1tTJJ)
  - [Anatomy of Matplotlib - Root & Aizenman - SciPy 2018](https://www.youtube.com/watch?v=6gdNUDs6QPc)
  - [Docker](https://www.youtube.com/watch?v=fqMOX6JJhGo): Nail down the basics with this tutorial from freeCodeCamp.
  - [SQL](https://selectstarsql.com/): Interactive book, aims to be "the best place on the internet for learning SQL" - you decide.
  - [Git](https://missing.csail.mit.edu/2020/version-control/): Go beyond typing commands blindly - understand git's data model.
  - [Git-Advanced](https://www.youtube.com/watch?v=qsTthZi23VE): Be more productive with these few more advanced concepts, e.g., rebase, cherry-picking, etc.
  - [fast.ai](https://www.fast.ai/): A myriad of learning resources – ML, python, developer tools, etc.
  - [Setosa: visual explanations](https://setosa.io/)
  - [Transformers & Attention](https://www.youtube.com/watch?v=yGTUuEx3GkA): A great explanation by V. Warmerdam at Rasa Whiteboard series.
  - [The math behind Attention: Keys, Queries, and Values matrices](https://www.youtube.com/watch?v=UPtG_38Oq8o): Geometric intuitions behind attention mechanism, a beautiful piece by L. Serrano.
  - [Load balancing with great visualizations](https://samwho.dev/load-balancing/)
  - [A half-hour lo learn Rust](https://fasterthanli.me/articles/a-half-hour-to-learn-rust): An entertaining masterpiece to quickly get your eyes reading the most beloved programming language.
  - [The missing semester in your CS education](https://www.youtube.com/watch?v=5WyOlYCrjUs&list=PLrZy_FnT2vQ30DPqr8LnZaMpkWzTbQTg_): Learn about the shell, vim, git, command-line tools, etc.
  - [(German) Setup Traefik with Docker Compose and Let's Encrypt](https://www.youtube.com/watch?v=PgICQblfWeY)

## Talks
  - [Choose Boring Technology – Dan McKinley](https://boringtechnology.club/)
  - [Facts and Myths about Python names and values - Ned Batchelder - PyCon 2015](https://www.youtube.com/watch?v=_AEJHKGk9ns)
  - [Statistics for Hackers - Jake van der Plas - PyCon 2016](https://www.youtube.com/watch?v=Iq9DzN6mvYA)
  - [Built in Super Heroes - David Beazley - PyData 2016](https://www.youtube.com/watch?v=lyDLAutA88s)
  - [Computational Statistics - Allen Downey - SciPy 2017](https://www.youtube.com/watch?v=He9MCbs1wgE)
  - [A Bluffer's Guide to Dimension Reduction - Leland McInnes - PyData 2018](https://www.youtube.com/watch?v=9iol3Lk6kyU)
  - [Untitled12 - Vincent Warmerdam - PyData 2019](https://www.youtube.com/watch?list=PLGVZCDnMOq0pDxc2cSp_N42M4OPfLgtBD&v=yXGCKqo5cEYt)
  - [Gaussian Progress – Vincent Warmerdam - PyData 2019](https://www.youtube.com/watch?v=aICqoAG5BXQ)

## Youtube channels
  - [3brown1blue](https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw): One of the best teachers in the internet. Ever.
  - [Corey Schafer](https://www.youtube.com/channel/UCCezIgC97PvUuR4_gbFUs5g): Hands down one of the best Python resources out there.
  - [anthonywritescode](https://www.youtube.com/channel/UC46xhU1EH7aywEgvA9syS3w): Mostly (not only) Python features, tools & idioms explained.
  - [Real Python](https://www.youtube.com/channel/UCI0vQvr9aFn27yR6Ej6n5UA)
  - [Luis serrano](https://www.youtube.com/channel/UCgBncpylJ1kiVaPyP-PZauQ): Machine learning algorithms and intuitions, in simple words.
  - [Luke Smith](https://www.youtube.com/channel/UC2eYFnH61tmytImy1mTYvhA): Unix, vim, latex, markdown, free-software, etc.
  - [Python Engineer](https://www.youtube.com/channel/UCbXgNpp0jedKWcQiULLbDTA)
  - [Ben Lambert](https://www.youtube.com/user/SpartacanUsuals): Stats, ML, Bayesian stuff.
  - [Statsquest – Josh Starmer](https://www.youtube.com/user/joshstarmer): Stats, machine learning, algorithms, bam!
  - [Arxiv Insights](https://www.youtube.com/channel/UCNIkB2IeJ-6AmZv7bQ1oBYg): Machine learning papers explained and discussed.

## Blogs
  - [Vincent Warmerdam](https://koaning.io): Data, machine learning, algorithms – and nice drawings.
  - [Max Halford](http://maxhalford.github.io)
  - [Adam Johnson](https://adamj.eu/tech): Mostly Python, tackling core aspects of the language.
  - [Squirrel, Not Squirrel](https://notsquirrel.com/pca/): Amazing PCA explanation.
  - [Michael Nielsen](http://cognitivemedium.com/)
  - [MLU-EXPLAIN](https://mlu-explain.github.io/): Visual explanations of core machine learning concepts.

## Podcasts
### Python & Co.
  - [Podcast.__init__](https://www.pythonpodcast.com/episodes/)
  - [Talk python to me](https://talkpython.fm/)
  - [Python Bytes](https://pythonbytes.fm/episodes/all)
  - [dats'n'stats](http://www.pydata-podcast.com/)
  - [The Real Python](https://realpython.com/podcasts/rpp/)
  - [Python Podcast (in German)](https://python-podcast.de/show/)

  
### Data, ML, Maths, etc.
  - [Vanishing Gradients - Hugo Bowne-Anderson](https://vanishinggradients.fireside.fm/)
  - [The Gradient Podcast](https://thegradientpub.substack.com/s/podcast)
  - [The Robot Brains Podcast - Peter Abeel](https://www.therobotbrains.ai/)
  - [Practical AI](https://open.spotify.com/episode/0dXmvOSo6bvcVRjUY6qWI8?si=r1EyetnTSaWnU8KjRf6Drg)
  - [AI in action](https://open.spotify.com/show/6z0wTS6N8Lwj8zuZHeFKLx)
  - [Machine Learning Street Talks](https://www.youtube.com/channel/UCMLtBahI5DMrt0NPvDSoIRQ/videos)
  - [Complexity - Sta. Fe Institute](https://www.santafe.edu/culture/podcast)
  - [This week in machine learning](https://twimlai.com/)
  - [Underrated ML](https://www.underratedml.com/)
  - [Talking Machines](https://www.thetalkingmachines.com/)
  - [Numberphile](https://www.numberphile.com/podcast)
  - [Data skeptic](https://dataskeptic.com/)
  - [Linear Digressions](http://lineardigressions.com/)
  - [Gradient dissent: Weights and biases](https://open.spotify.com/show/7o9r3fFig3MhTJwehXDbXm?si=d7Ncp7nXQ7C1O7wu0Oxvqg)
  - [Dataframed](https://www.datacamp.com/community/podcast)
  
  
### Discussion, interviews, philosophy
  - [Sean Carrol's Mindscape](https://www.preposterousuniverse.com/podcast/)
  - [The knowledge project](https://fs.blog/knowledge-project/)
  - [Not so standard deviations](http://nssdeviations.com/)
  - [Adversarial Learning](https://adversariallearning.com/)
  - [Brain inspired](https://braininspired.co/)
  - [Stephen Wolfram podcast](https://soundcloud.com/stephenwolfram)
  - [Chai Tea Data Science](https://chaitimedatascience.com/)
  - [DeepMind Podcast](https://deepmind.com/blog/article/welcome-to-the-deepmind-podcast)
  - [Towards data science](https://towardsdatascience.com/podcast/home)
  - [The data exchange](https://thedataexchange.media/episodes/)

## Tools
  - [ezgif: Create, edit and convert GIFs](https://ezgif.com/)
